name: Build and deploy GH Pages

on:
  push:
    branches:
      - master   # Only deploy on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Zola
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          # Branch to deploy to
          PAGES_BRANCH: gh-pages
          # Token for authentication (automatic token is enough)
          TOKEN: ${{ secrets.TOKEN }}
          # Repository to deploy to
          REPOSITORY: LazyCode2/blog
